### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Hikkitk** [marsn3/mudaetracker#1]
i try many times and i dont get the bot up
![image_2022-05-05_133347589](https://user-images.githubusercontent.com/103954252/166980257-7d911254-d4e2-4342-8eb9-39a56c3198d1.png)

**Comment by marsn3** [comment]
Sorry about that, i originally ran the bot on my server so i didn't test if it would be compatible with windows. I updated the code to hopefully fix this, but there might be other problems when running it on windows. Feel free to reopen this issue or create another one if you have any other problems.

**Comment by Hikkitk** [comment]
You have discord? i can add you and tell you for any problems asap
